services:
  redis:
    image: redis:7.4.0
    ports:
      - 6380:6379

  postgres:
    image: postgres:16.4
    ports:
      - 5432:5432
    volumes:
      - ./docker/init_database:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=password